version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - postgres:/data/postgres

  service:
    build:
      dockerfile: Dockerfile
    container_name: hezzl_app
    depends_on:
      - postgres
    environment:
      PG_DSN: ${PG_DSN}
    ports:
      - "8000:8000"


volumes:
  postgres:

